"""Tests for HTML audit report generation."""

from __future__ import annotations

from pathlib import Path

from matt_stack.auditors.base import AuditFinding, AuditReport, AuditType, Severity
from matt_stack.auditors.html_report import generate_html_report


def _finding(
    severity: Severity = Severity.WARNING,
    category: AuditType = AuditType.QUALITY,
    message: str = "Test finding",
    suggestion: str = "Fix it",
) -> AuditFinding:
    return AuditFinding(
        category=category,
        severity=severity,
        file=Path("app.py"),
        line=10,
        message=message,
        suggestion=suggestion,
    )


def _make_report(findings: list[AuditFinding] | None = None) -> AuditReport:
    return AuditReport(
        findings=findings or [],
        auditors_run=["quality"],
    )


class TestGenerateHtmlReport:
    """Tests for generate_html_report."""

    def test_returns_valid_html(self, tmp_path: Path) -> None:
        report = _make_report([_finding()])
        html = generate_html_report(report, tmp_path)
        assert html.startswith("<!DOCTYPE html>")
        assert "</html>" in html

    def test_contains_all_sections(self, tmp_path: Path) -> None:
        report = _make_report([_finding()])
        html = generate_html_report(report, tmp_path)
        assert "<header>" in html
        assert "Total Findings" in html
        assert "Errors" in html
        assert "Warnings" in html
        assert "Info" in html
        assert '<div class="filters">' in html
        assert "<table" in html
        assert "<footer>" in html
        assert "Generated by matt-stack audit" in html

    def test_contains_css_and_js(self, tmp_path: Path) -> None:
        report = _make_report([_finding()])
        html = generate_html_report(report, tmp_path)
        assert "<style>" in html
        assert "</style>" in html
        assert "<script>" in html
        assert "</script>" in html

    def test_empty_report_works(self, tmp_path: Path) -> None:
        report = _make_report([])
        html = generate_html_report(report, tmp_path)
        assert "<!DOCTYPE html>" in html
        assert "No findings" in html
        assert "Total Findings" in html
        # Should show zero counts
        assert ">0<" in html

    def test_findings_appear_in_table(self, tmp_path: Path) -> None:
        report = _make_report(
            [
                _finding(severity=Severity.ERROR, message="Critical bug"),
                _finding(severity=Severity.WARNING, message="Minor issue"),
                _finding(severity=Severity.INFO, message="Just info"),
            ]
        )
        html = generate_html_report(report, tmp_path)
        assert "Critical bug" in html
        assert "Minor issue" in html
        assert "Just info" in html
        assert "badge-error" in html
        assert "badge-warning" in html
        assert "badge-info" in html

    def test_summary_counts_correct(self, tmp_path: Path) -> None:
        report = _make_report(
            [
                _finding(severity=Severity.ERROR),
                _finding(severity=Severity.ERROR),
                _finding(severity=Severity.WARNING),
                _finding(severity=Severity.INFO),
            ]
        )
        html = generate_html_report(report, tmp_path)
        # Total = 4, errors = 2, warnings = 1, info = 1
        # Check the card values contain the right numbers
        assert ">4<" in html  # total
        assert ">2<" in html  # errors
        assert ">1<" in html  # warnings and info

    def test_special_characters_escaped(self, tmp_path: Path) -> None:
        xss_msg = '<script>alert("xss")</script>'
        report = _make_report([_finding(message=xss_msg)])
        html = generate_html_report(report, tmp_path)
        # The raw script tag should NOT appear unescaped in the table body
        assert xss_msg not in html
        assert "&lt;script&gt;" in html

    def test_project_name_in_title(self, tmp_path: Path) -> None:
        project = tmp_path / "my-cool-project"
        project.mkdir()
        report = _make_report([_finding()])
        html = generate_html_report(report, project)
        assert "my-cool-project" in html
        assert "<title>Audit Report" in html

    def test_suggestion_appears(self, tmp_path: Path) -> None:
        report = _make_report([_finding(suggestion="Use typing.Optional")])
        html = generate_html_report(report, tmp_path)
        assert "Use typing.Optional" in html

    def test_filter_buttons_present(self, tmp_path: Path) -> None:
        report = _make_report([_finding()])
        html = generate_html_report(report, tmp_path)
        assert 'data-filter="all"' in html
        assert 'data-filter="error"' in html
        assert 'data-filter="warning"' in html
        assert 'data-filter="info"' in html

    def test_data_attributes_on_rows(self, tmp_path: Path) -> None:
        report = _make_report([_finding(severity=Severity.ERROR, category=AuditType.QUALITY)])
        html = generate_html_report(report, tmp_path)
        assert 'data-severity="error"' in html
        assert 'data-category="quality"' in html

    def test_sortable_headers(self, tmp_path: Path) -> None:
        report = _make_report([_finding()])
        html = generate_html_report(report, tmp_path)
        assert 'data-col="0"' in html
        assert 'data-col="4"' in html
